version: "3.8"

services:
  nginx:
    image: library/nginx:latest
    restart: 'on-failure'
    volumes:
      - ./.docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./:/repo
    working_dir: /repo
    depends_on:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fcgi-demo.rule=Host(`fastcgi-demo.hollo.me`)"
      - "traefik.http.routers.fcgi-demo.tls=true"
    networks:
      - default
      - fcgidemo

  web:
    image: library/php:8.0-fpm-alpine
    restart: 'on-failure'
    depends_on:
      - worker
    volumes:
      - ./:/repo
      - worker-unix-domain-socket:/socket
    working_dir: /repo
    networks:
      - fcgidemo

  worker:
    build:
      context: ./.docker/php/worker
      dockerfile: Dockerfile
    restart: 'on-failure'
    volumes:
      - ./:/repo
      - worker-unix-domain-socket:/socket
    working_dir: /repo
    networks:
      - fcgidemo

  composer:
    image: library/composer:2
    volumes:
      - ./:/repo
      - ~/.composer:/.composer
    working_dir: /repo
    networks:
      - fcgidemo

networks:
  default:
    external:
      name: "gateway"
  fcgidemo:

volumes:
  worker-unix-domain-socket:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=10m