version: "3.8"

services:
  nginx:
    image: library/nginx:latest
    restart: 'on-failure'
    volumes:
      - ./.docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./:/repo
    working_dir: /repo
    depends_on:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fcgi-demo.rule=Host(`fastcgi-demo.hollo.me`)"
      - "traefik.http.routers.fcgi-demo.tls=true"
    networks:
      - default
      - fcgidemo

  web:
    build:
      context: ./.docker/php/web
      dockerfile: Dockerfile
    restart: 'on-failure'
    volumes:
      - ./:/repo
    working_dir: /repo
    networks:
      - fcgidemo

  composer:
    image: library/composer:2
    volumes:
      - ./:/repo
      - ~/.composer:/.composer
    working_dir: /repo
    networks:
      - fcgidemo

networks:
  default:
    external:
      name: "gateway"
  fcgidemo:
